### ISSUE TITLE
Can I avoid supplying S3 credentials if my MLFlow server is proxying access

### ISSUE THREAD

**Issue by KPLauritzen** [dingobar/mlflow-mlserver-docker#1]
MLFlow Tracking Server has recently(?) added an option to proxy access to the artifacts. 
See https://mlflow.org/docs/latest/tracking.html#scenario-5-mlflow-tracking-server-enabled-with-proxied-artifact-storage-access
This means that as a user I don't need to care about where and how the models are stored, I can just ask MLFlow to supply them to me. 

I'm not sure if there is any programmatic way to check for this, but if there is, it would be very convenient to use,

**Comment by martimors** [comment]
I don't see why not. Looks like you should be able to give it `mlflow-artifacts:/run_id/model`.
